/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDataManagementRouteImport } from './routes/_authenticated/data-management'
import { Route as AuthenticatedHousesRouteImport } from './routes/_authenticated/houses'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated/team.index'
import { Route as AuthenticatedTeamCswCswIdRouteImport } from './routes/_authenticated/team.csw.$cswId'
import { Route as AuthenticatedTeamSupervisorSupervisorIdRouteImport } from './routes/_authenticated/team.supervisor.$supervisorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataManagementRoute =
  AuthenticatedDataManagementRouteImport.update({
    id: '/data-management',
    path: '/data-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHousesRoute = AuthenticatedHousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamCswCswIdRoute =
  AuthenticatedTeamCswCswIdRouteImport.update({
    id: '/team/csw/$cswId',
    path: '/team/csw/$cswId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamSupervisorSupervisorIdRoute =
  AuthenticatedTeamSupervisorSupervisorIdRouteImport.update({
    id: '/team/supervisor/$supervisorId',
    path: '/team/supervisor/$supervisorId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/data-management': typeof AuthenticatedDataManagementRoute
  '/houses': typeof AuthenticatedHousesRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
  '/team/csw/$cswId': typeof AuthenticatedTeamCswCswIdRoute
  '/team/supervisor/$supervisorId': typeof AuthenticatedTeamSupervisorSupervisorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/data-management': typeof AuthenticatedDataManagementRoute
  '/houses': typeof AuthenticatedHousesRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamIndexRoute
  '/team/csw/$cswId': typeof AuthenticatedTeamCswCswIdRoute
  '/team/supervisor/$supervisorId': typeof AuthenticatedTeamSupervisorSupervisorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/data-management': typeof AuthenticatedDataManagementRoute
  '/_authenticated/houses': typeof AuthenticatedHousesRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
  '/_authenticated/team/csw/$cswId': typeof AuthenticatedTeamCswCswIdRoute
  '/_authenticated/team/supervisor/$supervisorId': typeof AuthenticatedTeamSupervisorSupervisorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/data-management'
    | '/houses'
    | '/map'
    | '/profile'
    | '/settings'
    | '/team/'
    | '/team/csw/$cswId'
    | '/team/supervisor/$supervisorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/data-management'
    | '/houses'
    | '/map'
    | '/profile'
    | '/settings'
    | '/team'
    | '/team/csw/$cswId'
    | '/team/supervisor/$supervisorId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/data-management'
    | '/_authenticated/houses'
    | '/_authenticated/map'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/team/'
    | '/_authenticated/team/csw/$cswId'
    | '/_authenticated/team/supervisor/$supervisorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-management': {
      id: '/_authenticated/data-management'
      path: '/data-management'
      fullPath: '/data-management'
      preLoaderRoute: typeof AuthenticatedDataManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/houses': {
      id: '/_authenticated/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof AuthenticatedHousesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/csw/$cswId': {
      id: '/_authenticated/team/csw/$cswId'
      path: '/team/csw/$cswId'
      fullPath: '/team/csw/$cswId'
      preLoaderRoute: typeof AuthenticatedTeamCswCswIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team/supervisor/$supervisorId': {
      id: '/_authenticated/team/supervisor/$supervisorId'
      path: '/team/supervisor/$supervisorId'
      fullPath: '/team/supervisor/$supervisorId'
      preLoaderRoute: typeof AuthenticatedTeamSupervisorSupervisorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDataManagementRoute: typeof AuthenticatedDataManagementRoute
  AuthenticatedHousesRoute: typeof AuthenticatedHousesRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
  AuthenticatedTeamCswCswIdRoute: typeof AuthenticatedTeamCswCswIdRoute
  AuthenticatedTeamSupervisorSupervisorIdRoute: typeof AuthenticatedTeamSupervisorSupervisorIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDataManagementRoute: AuthenticatedDataManagementRoute,
  AuthenticatedHousesRoute: AuthenticatedHousesRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
  AuthenticatedTeamCswCswIdRoute: AuthenticatedTeamCswCswIdRoute,
  AuthenticatedTeamSupervisorSupervisorIdRoute:
    AuthenticatedTeamSupervisorSupervisorIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
